/// Flutter icons IconsMotel
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
import 'package:flutter/widgets.dart';

class IconsMotel {
  IconsMotel._();

  static const _kFontFam = 'IconsMotel';
  static const _kFontPkg = null;

  static const IconData automotel_icon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hotel_icon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData motel_icon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
